#!/bin/sh

# Dpkg remove does prerm --> remove installed files --> postrm
# Dpkg purge does remove --> postrm
# Hence postrm is the common script run for both remove + purge

set -e

echo "Cleaning up in postrm"

echo "Removing /usr/local/include/ImageMagick-devel"
rm -rf /usr/local/include/ImageMagick-devel
exit 0
