#!/bin/sh
set -e
DIR=/usr/local/include/ImageMagick-devel
if [ ! -d "$DIR" ]; then
	echo 'imagemagick-devel is already installed. Please use dpkg --purge imagemagick-devel before installing again'
	exit 2
fi
exit 0
